### ISSUE TITLE
Too much clutter from avatars on the homepage, restrict URL match to /item & /user

### ISSUE THREAD

**Issue by ptrcvc** [ekofi/hn_avatar_ext#1]
There is too much clutter from adding the avatars onto the homepage, it makes it difficult to focus on the article titles, so the avatars should only bee seen on the comments page & your profile page.

I'm not sure how to specifically omit the homepage, so instead I suggest the extension only match /item & /user.

(/item is the comments page for a particular post.)

In `manifest.json` :
``` 
  "content_scripts": [
    {
      "matches": ["https://news.ycombinator.com/*"],
      "js": ["background.js"]
    }
  ],
```
this should become: 
``` 
  "content_scripts": [
    {
      "matches": [
        "https://news.ycombinator.com/item*",
        "https://news.ycombinator.com/user*"
      ],
      "js": ["background.js"]
    }
  ],
```

**Comment by ekofi** [comment]
Done. Thanks for this, sorry for late reply
